plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.flic2'
version = '0.2.2'

android {
  namespace "expo.modules.flic2"

  defaultConfig {
    versionCode 1
    versionName "0.2.2"
    minSdkVersion 24
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }

  kotlinOptions {
    jvmTarget = JavaVersion.VERSION_17.majorVersion
  }
}

repositories {
  mavenCentral()
  maven { url 'https://jitpack.io' }
}

dependencies {
  implementation 'com.github.50ButtonsEach:flic2lib-android:2.+'
}
